alias ls='ls -F --color=auto'
alias ll='ls -l'
alias cl='clear; ls'
alias cls='cl'
alias cll='clear; ls -l'
alias llm='ll | more'
alias lls='ll | sort -n -r -k 9'
alias llt='ls -ltr'
alias llsm='ll | sort -n -r -k 9 | more'
alias cllm='clear; llm'
alias clls='clear; lls'
alias cllt='clear; llt'
alias cllsm='clear; llsm'

alias c='cd ..'
alias e='exit'
alias m='clear; more'
alias b='cd ~/bin'
alias r='fc -e -'
alias t='cd ~/tmp'

alias cp='cp -v'
alias mv='mv -iv'
alias rm='rm -v'
alias md='mkdir'
alias rd='rmdir'
alias vi='gvim'
alias vir='vi -R'

alias du='du -ch'
alias pdb='perl -d'

alias pack='pack -e -d'
alias unpack='unpack -e'

alias env='env | sort'

alias kill='kill -9'
alias calc='gnome-calculator &'
